# -*- coding: utf-8 -*-
"""260319_app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tRP95HRQPM-NJYuoZCuTzDVPf_gYfQdo
"""

#pip install streamlit

import streamlit as st
import pandas as pd
import numpy as np
import io

# functions for time conversion
def time_to_minutes(time_str):
    try:
        hours = int(time_str[:2])
        minutes = int(time_str[2:])
        return hours * 60 + minutes
    except:
        return 0

def minutes_to_time(minute):
    if pd.isna(minute):
        return ""
    hours = int(minute // 60)
    minutes = int(minute % 60)
    return f"{hours:02d}{minutes:02d}"

st.set_page_config(page_title = "Flight Connection Analysis", layout = "wide")
st.title("✈️ Flight Connection Analysis")

st.markdown("""Vui lòng tải lên file dữ liệu CSV để bắt đầu.""")

# 1. Upload CSV
uploaded_file = st.file_uploader("Tải lên file dữ liệu CSV (Upload your Flight Data CSV)", type = ['csv'])

if uploaded_file is not None:
    # Load data
    try:
        data = pd.read_csv(uploaded_file)
        st.success("Tải file thành công!")
    except Exception as e:
        st.error(f"Lỗi khi đọc file: {e}")
        st.stop()

    # Standardize column names or ensure required columns exist
    required_cols = ['YEAR', 'WEEK', 'TIMERANGE', 'LEG', 'DEPTIME', 'ARRTIME', 'LF']
    missing_cols = [col for col in required_cols if col not in data.columns]
    if missing_cols:
        st.error(f"File upload thiếu các cột bắt buộc: {missing_cols}")
        st.stop()

    # Sidebar inputs
    st.sidebar.header("Tiêu chí lọc (Filters)")

    # Year selection
    years = sorted(data['YEAR'].dropna().unique().tolist())
    selected_year = st.sidebar.selectbox("Chọn Year", years)

    # Leg Type selection
    leg_type = st.sidebar.radio("Chọn loại hành trình", ["Inbound", "Outbound"])

    # Leg selection
    legs = sorted(data[data['YEAR'] == selected_year]['LEG'].dropna().unique().tolist())
    selected_leg = st.sidebar.selectbox("Chọn Leg", legs)

    # Time Range selection
    time_ranges = sorted(data[(data['YEAR'] == selected_year) & (data['LEG'] == selected_leg)]['TIMERANGE'].dropna().unique().tolist())
    if not time_ranges:
        st.sidebar.warning("Không có Time Range cho Year và Leg đã chọn.")
    else:
        selected_time_range = st.sidebar.selectbox("Chọn Time Range", time_ranges)

        # Process Button
        if st.sidebar.button("Phân tích (Analyze)"):
            with st.spinner("Đang xử lý dữ liệu..."):
                # --- Step 1: Input Info Processing ---
                filtered_data = data[(data['YEAR'] == selected_year) &
                                     (data['LEG'] == selected_leg) &
                                     (data['TIMERANGE'] == selected_time_range)]

                if filtered_data.empty:
                    st.error("Không tìm thấy dữ liệu phù hợp với các tiêu chí lọc.")
                else:
                    return_df = filtered_data[['YEAR', 'WEEK', 'LEG', 'DEPTIME', 'ARRTIME', 'TIMERANGE', 'LF']].copy()

                    if leg_type.lower() == 'inbound':
                        return_df['Time_Str'] = return_df['ARRTIME'].astype(str).str.zfill(4)
                        return_df['Time_Mean'] = return_df['Time_Str'].apply(time_to_minutes)
                        time_column_name_for_output = 'AvgArrTime'
                    else:
                        return_df['Time_Str'] = return_df['DEPTIME'].astype(str).str.zfill(4)
                        return_df['Time_Mean'] = return_df['Time_Str'].apply(time_to_minutes)
                        time_column_name_for_output = 'AvgDepTime'

                    result = return_df.groupby(['YEAR', 'WEEK', 'LEG', 'TIMERANGE']).agg(
                        LF=('LF', 'mean'),
                        Avg_Minutes=('Time_Mean', 'mean')
                    ).reset_index()

                    result[time_column_name_for_output] = result['Avg_Minutes'].apply(minutes_to_time)
                    input_df = result[['YEAR', 'WEEK', 'LEG', 'TIMERANGE', 'LF', time_column_name_for_output]]

                    # Pivot input info
                    try:
                        df_input_info_pivot = input_df.pivot(index=['YEAR', 'LEG', 'TIMERANGE'], columns='WEEK', values='LF').reset_index()
                        df_input_info_pivot.columns.name = None
                    except:
                        df_input_info_pivot = input_df # fallback

                    st.subheader("📋 Chi tiết dữ liệu đầu vào (User Input Details)")
                    st.dataframe(df_input_info_pivot, use_container_width=True)

                    # --- Step 2: Connection logic ---
                    result_df = pd.DataFrame()

                    if leg_type.lower() == 'inbound':
                        target_arrival_airport = selected_leg[-3:]
                        original_leg_data = data[(data['YEAR'] == selected_year) &
                                                 (data['LEG'] == selected_leg) &
                                                 (data['TIMERANGE'] == selected_time_range)].copy()
                        original_leg_data['Time_Str'] = original_leg_data['ARRTIME'].astype(str).str.zfill(4)
                        original_leg_data['Time_Min'] = original_leg_data['Time_Str'].apply(time_to_minutes)

                        original_leg_weekly_arrival_time = original_leg_data.groupby('WEEK')['Time_Min'].mean().reset_index()
                        original_leg_weekly_arrival_time = original_leg_weekly_arrival_time.rename(columns={'Time_Min': 'original_leg_avg_arrival_time'})

                        filtered_context_data = data[(data['YEAR'] == selected_year)].copy()
                        potential_outbound_legs = filtered_context_data[filtered_context_data['LEG'].str.startswith(target_arrival_airport, na=False)].copy()

                        if not potential_outbound_legs.empty:
                            potential_outbound_legs['DEPTIME_Str'] = potential_outbound_legs['DEPTIME'].astype(str).str.zfill(4)
                            potential_outbound_legs['DEPTIME_Min'] = potential_outbound_legs['DEPTIME_Str'].apply(time_to_minutes)

                            grouped_outbound = potential_outbound_legs.groupby(['YEAR', 'WEEK', 'LEG', 'TIMERANGE']).agg(
                                LF=('LF', 'mean'),
                                avg_deptime_min=('DEPTIME_Min', 'mean')
                            ).reset_index()

                            grouped_outbound = pd.merge(grouped_outbound, original_leg_weekly_arrival_time, on='WEEK', how='left')
                            grouped_outbound['DURATION_in_minutes'] = grouped_outbound['avg_deptime_min'] - grouped_outbound['original_leg_avg_arrival_time']
                            grouped_outbound['DURATION_in_minutes'] = grouped_outbound['DURATION_in_minutes'].apply(lambda x: x + 24 * 60 if x < 0 else x)
                            grouped_outbound['DURATION_in_minutes'] = grouped_outbound['DURATION_in_minutes'].fillna(0)
                            grouped_outbound['DURATION'] = grouped_outbound['DURATION_in_minutes'].apply(minutes_to_time)
                            grouped_outbound['DEPTIME'] = grouped_outbound['avg_deptime_min'].apply(minutes_to_time)

                            result_df = grouped_outbound[['YEAR', 'WEEK', 'LEG', 'TIMERANGE', 'LF', 'DURATION', 'DEPTIME']].copy()
                            result_df = result_df.sort_values(by=['YEAR', 'WEEK', 'LEG', 'TIMERANGE']).reset_index(drop=True)

                            # Pivot logic for Inbound
                            try:
                                pivot_result = result_df.pivot(index=['LEG', 'TIMERANGE', 'DEPTIME', 'DURATION'], columns='WEEK', values='LF').reset_index()
                                pivot_result.columns.name = None
                            except:
                                pivot_result = result_df

                            st.subheader("🟢 Inbound Legs (Inbound Legs Output)")
                            st.dataframe(pivot_result, use_container_width=True)

                            # Export feature
                            csv = pivot_result.to_csv(index=False).encode('utf-8')
                            st.download_button("Tải file Inbound (Download CSV)", csv, "inbound_result.csv", "text/csv")
                        else:
                            st.info("Không tìm thấy dữ liệu inbound matching.")

                    elif leg_type.lower() == 'outbound':
                        target_departure_airport = selected_leg[:3]
                        original_leg_data = data[(data['YEAR'] == selected_year) &
                                                 (data['LEG'] == selected_leg) &
                                                 (data['TIMERANGE'] == selected_time_range)].copy()

                        original_leg_data['Time_Str'] = original_leg_data['DEPTIME'].astype(str).str.zfill(4)
                        original_leg_data['Time_Min'] = original_leg_data['Time_Str'].apply(time_to_minutes)

                        original_leg_weekly_deptime = original_leg_data.groupby('WEEK')['Time_Min'].mean().reset_index()
                        original_leg_weekly_deptime = original_leg_weekly_deptime.rename(columns={'Time_Min': 'original_leg_avg_deptime'})

                        filtered_context_data = data[(data['YEAR'] == selected_year)].copy()
                        potential_inbound_legs = filtered_context_data[filtered_context_data['LEG'].str.endswith(target_departure_airport, na=False)].copy()

                        if not potential_inbound_legs.empty:
                            potential_inbound_legs['ARRTIME_Str'] = potential_inbound_legs['ARRTIME'].astype(str).str.zfill(4)
                            potential_inbound_legs['ARRTIME_Min'] = potential_inbound_legs['ARRTIME_Str'].apply(time_to_minutes)

                            grouped_inbound = potential_inbound_legs.groupby(['YEAR', 'WEEK', 'LEG', 'TIMERANGE']).agg(
                                LF=('LF', 'mean'),
                                avg_arrtime_min=('ARRTIME_Min', 'mean')
                            ).reset_index()

                            grouped_inbound = pd.merge(grouped_inbound, original_leg_weekly_deptime, on='WEEK', how='left')
                            grouped_inbound['DURATION_in_minutes'] = grouped_inbound['original_leg_avg_deptime'] - grouped_inbound['avg_arrtime_min']
                            grouped_inbound['DURATION_in_minutes'] = grouped_inbound['DURATION_in_minutes'].apply(lambda x: x + 24 * 60 if x < 0 else x)
                            grouped_inbound['DURATION_in_minutes'] = grouped_inbound['DURATION_in_minutes'].fillna(0)
                            grouped_inbound['DURATION'] = grouped_inbound['DURATION_in_minutes'].apply(minutes_to_time)
                            grouped_inbound['ARRTIME'] = grouped_inbound['avg_arrtime_min'].apply(minutes_to_time)

                            result_df = grouped_inbound[['YEAR', 'WEEK', 'LEG', 'TIMERANGE', 'LF', 'DURATION', 'ARRTIME']].copy()
                            result_df = result_df.sort_values(by=['YEAR', 'WEEK', 'LEG', 'TIMERANGE']).reset_index(drop=True)

                            # Pivot logic for Outbound
                            try:
                                pivot_result = result_df.pivot(index=['LEG', 'TIMERANGE', 'ARRTIME', 'DURATION'], columns='WEEK', values='LF').reset_index()
                                pivot_result.columns.name = None
                            except:
                                pivot_result = result_df

                            st.subheader("🔵 Outbound Legs (Outbound Legs Output)")
                            st.dataframe(pivot_result, use_container_width=True)

                            # Export feature
                            csv = pivot_result.to_csv(index=False).encode('utf-8')
                            st.download_button("Tải file Outbound (Download CSV)", csv, "outbound_result.csv", "text/csv")
                        else:
                            st.info("Không tìm thấy dữ liệu outbound matching.")

else:
    st.info("Vui lòng tải tệp CSV lên để tiếp tục.")