# -*- coding: utf-8 -*-
"""260319_app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tRP95HRQPM-NJYuoZCuTzDVPf_gYfQdo
"""

#pip install streamlit

# time to minutes
def time_to_minutes(time):
    hours = int(time[:2])
    minutes = int(time[2:])
    return hours * 60 + minutes

# minutes to time
def minutes_to_time(minute):
    hours = int(minute // 60)
    minutes = int(minute % 60)
    return f"{hours:02d}{minutes:02d}"

import streamlit as st
import pandas as pd

# --- CẤU HÌNH TRANG ---
st.set_page_config(page_title="Flight Connection Analysis", layout="wide")

st.title("📊 Flight Connection Analysis")

# --- SIDEBAR ---
with st.sidebar:
    st.header("Cài đặt dữ liệu")

    uploaded_file = st.file_uploader("Tải lên file CSV dữ liệu", type=["csv"])

    if uploaded_file is not None:
        # 1. Đọc dữ liệu gốc
        data = pd.read_csv(uploaded_file)

        # Bước 1: Chọn Year
        list_year = sorted(data['YEAR'].unique())
        selected_year = st.selectbox("1. Chọn Year", list_year)
        df_year = data[data['YEAR'] == selected_year]

        # Bước 2: Chọn Leg (Lọc theo Year)
        list_leg = sorted(df_year['LEG'].unique())
        selected_leg = st.selectbox("2. Chọn Leg", list_leg)
        df_leg = df_year[df_year['LEG'] == selected_leg]

        # Bước 3: Chọn Time Range (CHỈ lọc theo Year và Leg)
        list_timerange = sorted(df_leg['TIMERANGE'].unique())
        selected_timerange = st.selectbox("3. Chọn Time Range", list_timerange)

        # Bước 4: Lựa chọn Inbound/Outbound (Đây là Option, không phải cột trong data)
        selected_type = st.radio("4. Loại hành trình", ["Inbound", "Outbound"])

        st.divider()
        # Nút ấn cuối cùng
        run_button = st.button("🚀 Bắt đầu xử lý")

# --- PHẦN XỬ LÝ LOGIC ---
if uploaded_file is not None:
    if run_button:
        # Lọc dữ liệu thô theo các thông số kỹ thuật (Year, Leg, TimeRange)
        processed_df = data[
            (data['YEAR'] == selected_year) &
            (data['LEG'] == selected_leg) &
            (data['TIMERANGE'] == selected_timerange)
        ].copy()

        if processed_df.empty:
            st.warning("Không có dữ liệu phù hợp với lựa chọn.")
        else:
            # --- ĐIỀU HƯỚNG LOGIC THEO OPTION CHỌN ---
            if selected_type == "Inbound":
                st.subheader(f"Kết quả phân tích: {selected_type}")
                def inbound(leg_input, year, time_range):
                  outbound_legs_data = []
                  target_arrival_airport = leg_input[-3:]

                  # input data (no longer filtering by specific week, gets all weeks for the selected year, leg, time_range)
                  original_leg_data = data[(data['YEAR'] == year) & (data['LEG'] == leg_input) & (data['TIMERANGE'] == time_range)].copy()

                  # format arrival time cua leg input
                  original_leg_data['Time_Str'] = original_leg_data['ARRTIME'].astype(str).str.zfill(4)
                  original_leg_data['Time_Min'] = original_leg_data['Time_Str'].apply(time_to_minutes)
                  # tinh avg arrival time PER WEEK
                  original_leg_weekly_arrival_time = original_leg_data.groupby('WEEK')['Time_Min'].mean().reset_index()
                  original_leg_weekly_arrival_time = original_leg_weekly_arrival_time.rename(columns={'Time_Min': 'original_leg_avg_arrival_time'})

                  # filter year (already contains all weeks)
                  filtered_context_data = data[(data['YEAR'] == year)].copy()

                  # filter cac leg co 3 ki tu dau giong 3 ki tu cuoi cua leg input
                  potential_outbound_legs = filtered_context_data[filtered_context_data['LEG'].str.startswith(target_arrival_airport)].copy()

                  if potential_outbound_legs.empty:
                    return pd.DataFrame(columns=['YEAR', 'WEEK', 'LEG', 'TIMERANGE', 'LF', 'DURATION', 'DEPTIME'])

                  # deptime theo tong so phut
                  potential_outbound_legs['DEPTIME_Str'] = potential_outbound_legs['DEPTIME'].astype(str).str.zfill(4)
                  potential_outbound_legs['DEPTIME_Min'] = potential_outbound_legs['DEPTIME_Str'].apply(time_to_minutes)

                  # group by leg, time range, WEEK de tinh LF, avg deptime
                  grouped_outbound = potential_outbound_legs.groupby(['YEAR', 'WEEK', 'LEG', 'TIMERANGE']).agg(LF = ('LF', 'mean'), avg_deptime_min = ('DEPTIME_Min', 'mean')).reset_index()

                  # tinh duration = avg deptime - avg arrival time (now merged by week)
                  grouped_outbound = pd.merge(grouped_outbound, original_leg_weekly_arrival_time, on='WEEK', how='left')
                  grouped_outbound['DURATION_in_minutes'] = grouped_outbound['avg_deptime_min'] - grouped_outbound['original_leg_avg_arrival_time']
                  grouped_outbound['DURATION_in_minutes'] = grouped_outbound['DURATION_in_minutes'].apply(lambda x: x + 24 * 60 if x < 0 else x)
                  grouped_outbound['DURATION_in_minutes'] = grouped_outbound['DURATION_in_minutes'].fillna(0) # fill NaN with 0
                  grouped_outbound['DURATION'] = grouped_outbound['DURATION_in_minutes'].apply(minutes_to_time)

                  # quy doi avg deptime ve format hhmm
                  grouped_outbound['DEPTIME'] = grouped_outbound['avg_deptime_min'].apply(minutes_to_time)

                  # output
                  result_df = grouped_outbound[['YEAR', 'WEEK', 'LEG', 'TIMERANGE', 'LF', 'DURATION', 'DEPTIME']].copy()
                  result_df = result_df.sort_values(by = ['YEAR', 'WEEK', 'LEG', 'TIMERANGE'], ascending = True).reset_index(drop = True)

                  return result_df
            else:
                st.subheader(f"Kết quả phân tích: {selected_type}")
                # Chèn logic hoặc gọi hàm outbound(processed_df) của bạn vào đây
                def outbound(leg_input, year, time_range):
                  target_departure_airport = leg_input[:3]

                  # input data (no longer filtering by specific week, gets all weeks for the selected year, leg, time_range)
                  original_leg_data = data[(data['YEAR'] == year) & (data['LEG'] == leg_input) & (data['TIMERANGE'] == time_range)].copy()

                  original_leg_data['Time_Str'] = original_leg_data['DEPTIME'].astype(str).str.zfill(4)
                  original_leg_data['Time_Min'] = original_leg_data['Time_Str'].apply(time_to_minutes)
                  # tinh avg deptime cua leg input PER WEEK
                  original_leg_weekly_deptime = original_leg_data.groupby('WEEK')['Time_Min'].mean().reset_index()
                  original_leg_weekly_deptime = original_leg_weekly_deptime.rename(columns={'Time_Min': 'original_leg_avg_deptime'})

                  # filter year (already contains all weeks)
                  filtered_context_data = data[(data['YEAR'] == year)].copy()

                  potential_inbound_legs = filtered_context_data[filtered_context_data['LEG'].str.endswith(target_departure_airport)].copy()

                  if potential_inbound_legs.empty:
                    return pd.DataFrame(columns = ['YEAR', 'WEEK', 'LEG', 'TIMERANGE', 'LF', 'DURATION', 'ARRTIME'])

                  potential_inbound_legs['ARRTIME_Str'] = potential_inbound_legs['ARRTIME'].astype(str).str.zfill(4)
                  potential_inbound_legs['ARRTIME_Min'] = potential_inbound_legs['ARRTIME_Str'].apply(time_to_minutes)

                  # group by theo leg, time range, WEEK de tinh total bkg, cap, LF
                  grouped_inbound = potential_inbound_legs.groupby(['YEAR', 'WEEK', 'LEG', 'TIMERANGE']).agg(LF = ('LF', 'mean'), avg_arrtime_min = ('ARRTIME_Min', 'mean')).reset_index()

                  # tinh duration = avg deptime leg input - avg arrival time current leg
                  grouped_inbound = pd.merge(grouped_inbound, original_leg_weekly_deptime, on='WEEK', how='left')
                  grouped_inbound['DURATION_in_minutes'] = grouped_inbound['original_leg_avg_deptime'] - grouped_inbound['avg_arrtime_min']
                  grouped_inbound['DURATION_in_minutes'] = grouped_inbound['DURATION_in_minutes'].apply(lambda x: x + 24 * 60 if x < 0 else x)
                  grouped_inbound['DURATION_in_minutes'] = grouped_inbound['DURATION_in_minutes'].fillna(0)
                  grouped_inbound['DURATION'] = grouped_inbound['DURATION_in_minutes'].apply(minutes_to_time)

                  # quy doi arrival time ve format hhmm
                  grouped_inbound['ARRTIME'] = grouped_inbound['avg_arrtime_min'].apply(minutes_to_time)

                  # output
                  result_df = grouped_inbound[['YEAR', 'WEEK', 'LEG', 'TIMERANGE', 'LF', 'DURATION', 'ARRTIME']].copy()
                  result_df = result_df.sort_values(by=['YEAR', 'WEEK', 'LEG', 'TIMERANGE'], ascending=True).reset_index(drop=True)

                  return result_df

            # --- HIỂN THỊ OUTPUT THEO FORMAT PIVOT ---
            try:
                # Dựa theo code chính: index=['LEG', 'TIMERANGE', 'DEPTIME', 'DURATION'], columns='WEEK', values='LF'
                result_df = processed_df.pivot_table(
                    index=['LEG', 'TIMERANGE', 'DEPTIME', 'DURATION'],
                    columns='WEEK',
                    values='LF'
                ).reset_index()

                # Hiển thị bảng
                st.dataframe(result_df, use_container_width=True)

                # Nút tải xuống
                csv = result_df.to_csv(index=False).encode('utf-8')
                st.download_button("📥 Tải file kết quả CSV", data=csv, file_name=f"{selected_type}_{selected_leg}.csv")

            except Exception as e:
                st.error(f"Lỗi khi tạo bảng Pivot: {e}")
                st.info("Hãy đảm bảo các cột LEG, TIMERANGE, DEPTIME, DURATION, WEEK, LF tồn tại trong dữ liệu.")
    else:
        st.info("👈 Hãy chọn các thông số và nhấn 'Bắt đầu xử lý'")
else:
    st.info("Vui lòng tải lên file CSV để bắt đầu.")