# -*- coding: utf-8 -*-
"""260319_app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tRP95HRQPM-NJYuoZCuTzDVPf_gYfQdo
"""

#pip install streamlit

import streamlit as st
import pandas as pd

# --- CẤU HÌNH TRANG ---
st.set_page_config(page_title="Flight Connection Analysis", layout="wide")

st.title("📊 Flight Connection Analysis (Dynamic Filter)")

# --- SIDEBAR: LỌC DỮ LIỆU BẬC THANG ---
with st.sidebar:
    st.header("Cài đặt dữ liệu")

    uploaded_file = st.file_uploader("Tải lên file CSV dữ liệu", type=["csv"])

    if uploaded_file is not None:
        # 1. Đọc dữ liệu gốc
        df = pd.read_csv(uploaded_file)

        # --- BẮT ĐẦU CHUỖI LỌC ĐỘNG ---

        # Bước 1: Chọn Year
        list_year = sorted(df['YEAR'].unique())
        selected_year = st.selectbox("1. Chọn Year", list_year)
        df_step1 = df[df['YEAR'] == selected_year]

        # Bước 2: Chọn INOUT (Dựa trên Year đã chọn)
        list_inout = sorted(df_step1['INOUT'].unique())
        selected_inout = st.selectbox("2. Loại hành trình (INOUT)", list_inout)
        df_step2 = df_step1[df_step1['INOUT'] == selected_inout]

        # Bước 3: Chọn Leg (Dựa trên Year + INOUT đã chọn)
        list_leg = sorted(df_step2['LEG'].unique())
        selected_leg = st.selectbox("3. Chọn Leg", list_leg)
        df_step3 = df_step2[df_step2['LEG'] == selected_leg]

        # Bước 4: Chọn Time Range (CHỈ hiện các khung giờ của Leg đã chọn ở trên)
        list_timerange = sorted(df_step3['TIMERANGE'].unique())
        selected_timerange = st.selectbox("4. Chọn Time Range", list_timerange)

        st.divider()
        # Nút ấn cuối cùng
        run_button = st.button("🚀 Bắt đầu xử lý")

# --- PHẦN HIỂN THỊ KẾT QUẢ ---
if uploaded_file is not None:
    if run_button:
        # Lọc dữ liệu cuối cùng theo tất cả các option
        final_df = df[
            (df['YEAR'] == selected_year) &
            (df['INOUT'] == selected_inout) &
            (df['LEG'] == selected_leg) &
            (df['TIMERANGE'] == selected_timerange)
        ].copy()

        if final_df.empty:
            st.warning("Không có dữ liệu phù hợp.")
        else:
            # Logic Pivot giống hệt hàm output trong code chính
            # Index: LEG, TIMERANGE, DEPTIME, DURATION | Columns: WEEK | Values: LF
            result_df = final_df.pivot_table(
                index=['LEG', 'TIMERANGE', 'DEPTIME', 'DURATION'],
                columns='WEEK',
                values='LF'
            ).reset_index()

            st.success(f"Đã xử lý xong dữ liệu cho {selected_leg}!")

            # Hiển thị bảng kết quả
            st.subheader("Kết quả phân tích (Pivot Table)")
            st.dataframe(result_df, use_container_width=True)

            # Tiện ích bổ sung: Tải file
            csv = result_df.to_csv(index=False).encode('utf-8')
            st.download_button("📥 Tải kết quả CSV", data=csv, file_name="result_output.csv")
    else:
        st.info("👈 Hãy chọn các thông số ở menu bên trái và nhấn 'Bắt đầu xử lý'")
else:
    st.info("Vui lòng tải lên file CSV để bắt đầu.")